%
global femobjectoptions

femobjectoptions = PARAMETERS(...
    'tolerancepoint',1e-12,...
    'tolerancelevelset',1e-9,...
    'nbsamplingsrandomsplit',100,...
    'path','/Users/Op/Documents/Recherche/GeM/FEMObject/',...
    'gmshpath',...
    '/Applications/gmsh-install/bin/',...%'/Applications/Gmsh-4.9.5/Gmsh.app/Contents/MacOS/',...%'/Applications/Gmsh-4.11.1/Gmsh.app/Contents/MacOS/',...
    'mmgpath','/Applications/mmg-install/bin/');
