%
global femobjectoptions

femobjectoptions = PARAMETERS(...
    'tolerancepoint',1e-12,...
    'tolerancelevelset',1e-9,...
    'nbsamplingsrandomsplit',100,...
    'path','/Users/matnoel/Documents/FEMObject/',...
    'gmshpath','/Applications/gmsh-install/bin/',...
    'mmgpath','/Applications/mmg-install/bin/');
