function disp(S)
% function disp(S)

f = {'mode',S.mode,...
    'nbelem',S.nbelem,...
    'nbnode',S.nbnode,...
    'nbgroupelem',S.nbgroupelem,...
    'nbfacets',length(S.facets),...
    'nbridges',length(S.ridges),...
    'nbpeaks',length(S.peaks),...
    'nbddl',S.nbddl,...
    'nbddlfree',length(getddlfree(S)),...
    'nbddlbloque',length(getddlbloque(S))
    };
v = struct(f{:});

disp(v)

if israndom(S)
    fprintf('MODEL''S (RANDVARS) \n')
    disp(RANDVARS(S))
end

fprintf('MODEL''S (MATERIALS)\n')

disp(MATERIALS(S))

