function mymatlab2tikz(pathname,filename,varargin)

matlab2tikz(fullfile(pathname,filename),...%'width','\figurewidth',...
    'height','\figureheight',...
    'encoding','UTF-8',...
    'parseStrings',false,...
    'showInfo',false,...
    varargin{:}...
    );
end