function [sol,out,pb] = crossBenchmark(order)

if nargin < 1
    order = 2 ;
end

model = QPModel('order',order,...
    'cellNum',[10 10],...
    'cellSize',[1 1],...
    'elementSize',[.05 .05],...
    'tolSVD',1e-6,...
    'verbose',true) ;

patterns = struct('name',{'uniform','cross','cross'},...
    'value',{100 1 1},...
    'size',{[] [.2 .2] [.2 .2]} ,...
    'center',{[] [.5 .5] [.5 .5]},...
    'offset',{[] [] [.35 0]}) ;
distribution = {setdiff(1:100,45) 45} ;
patternsTable = [1 1 ; 1 0 ; 0 1] ;

KAss = QPConductivityAssembler('model',model,...
    'patterns',patterns,...
    'patternsTable',patternsTable,...
    'distribution',distribution,...
    'tolSVD',getTolSVD(model),...
    'verbose',getVerbose(model)) ;
KAss = assemble(KAss) ; % to get conductivity and its bounds

diffAss = QPDiffusionAssembler('model',model,...
    'conductivity',getConductivity(KAss),...
    'conductivityBounds',getConductivityBounds(KAss),...
    'BC','PBC',...
    'source','corrector1',...
    'constantNullification','1point',...
    'tolSVD',getTolSVD(model),...
    'verbose',getVerbose(model)) ;
diffAss = setPenalty(diffAss,100) ;

pb = QPDiffusionProblem('model',model,...
    'conductivityAssembler',KAss,...
    'operatorAssembler',diffAss,...
    'tolerance',1e-3,...
    'verbose',getVerbose(model));

[sol,out,pb] = solve(pb,1:getOrder(pb)) ;

end