function [ddlnode,ddlgauss,ddlnodedual,ddlgaussdual] = calc_ddl(mat,elem)
% function [ddlnode,ddlgauss,ddlnodedual,ddlgaussdual]= calc_ddl(mat,elem)

syscoordnode = getsyscoord(elem);
syscoordgauss = getsyscoordlocal(elem);

ddlnode = DDL(DDLVECT('U',syscoordnode,'TRANS'),...
    DDLVECT('R',syscoordnode,'ROTA'));
ddlnodedual = DDL(DDLVECT('F',syscoordnode,'TRANS'),...
    DDLVECT('M',syscoordnode,'ROTA'));

% ddlgauss = DDL(DDLTENS2('E',syscoordgauss),...
%     DDLTENS2('G',syscoordgauss));
% ddlgaussdual = DDL(DDLTENS2('N',syscoordgauss),...
%     DDLTENS2('M',syscoordgauss));

switch class(elem)
    case {'DKT','DKQ'} % Kirchhoff-Love (classical) plate theory
        ddlgauss = DDL(DDLTENS2('E',syscoordgauss),...
            DDLTENS2('G',syscoordgauss),...
            DDLSCAL('DRZ'));
        ddlgaussdual = DDL(DDLTENS2('N',syscoordgauss),...
            DDLTENS2('M',syscoordgauss),...
            DDLSCAL('TAU'));
    case {'DST','DSQ','COQ4'} % Reissner-Mindlin (first-order shear) plate theory
        ddlgauss = DDL(DDLTENS2('E',syscoordgauss),...
            DDLTENS2('G',syscoordgauss),...
            DDLVECT('GZ',syscoordgauss),...
            DDLSCAL('DRZ'));
        ddlgaussdual = DDL(DDLTENS2('N',syscoordgauss),...
            DDLTENS2('M',syscoordgauss),...
            DDLVECT('Q',syscoordgauss),...
            DDLSCAL('TAU'));
    otherwise
        error(['Wrong elem type ' class(elem) ' for material type ' class(mat)])
        
end
